name: "Deploy Infra"
on:
  push:
    branches:
      - main
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Backup acme.json"
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ -f /root/Infra-com-Traefik/Infrastructure/traefik/certs/acme.json ]; then
              cp /root/Infra-com-Traefik/Infrastructure/traefik/certs/acme.json /tmp/acme.json.bak
            fi

      - name: "Copy Files"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/root/Infra-com-Traefik"
          debug: true

      - name: "Restore acme.json and set permissions"
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /root/Infra-com-Traefik/Infrastructure/traefik/certs
            if [ -f /tmp/acme.json.bak ]; then
              mv /tmp/acme.json.bak /root/Infra-com-Traefik/Infrastructure/traefik/certs/acme.json
            fi
            touch /root/Infra-com-Traefik/Infrastructure/traefik/certs/acme.json
            chmod 600 /root/Infra-com-Traefik/Infrastructure/traefik/certs/acme.json